global:
  worker:
    registrationKeySecret:
      name:
      key:
    tls:
      enable: false

# The ID of this cluster.
envoyClusterId: local-cluster-id

proxy:
  # Deprecated. Use sessionManagerServerWorkerServiceAddr instead.
  baseUrl:
  http:
    # pool size of the HTTP tunnel
    # Currently server supports only one channel per agent.
    poolSize: 1
  upgrade:
    # pool size of the HTTP upgrade tunnel
    poolSize: 10

# This default value works if session-manager-server runs in the same namespace.
sessionManagerServerWorkerServiceAddr: session-manager-server-worker-service-http:8082

httpPort: 8080

# Enable debug logging (true or false).
debugLogging: true

replicaCount: 1

serviceAccount:
  create: true

readinessProbe:
  successThreshold: 1
  failureThreshold: 3
  periodSeconds: 60
  timeoutSeconds: 5
  initialDelaySeconds: 5

image:
  repository: public.ecr.aws/cloudnatix/llm-operator/session-manager-agent
  pullPolicy: IfNotPresent

podAnnotations:
nodeSelector:
affinity:
tolerations:

version:

resources:
  requests:
    cpu: "250m"
    memory: "500Mi"
  limits:
    cpu: "250m"
