apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "session-manager-agent.fullname" . }}
  labels:
    {{- include "session-manager-agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  - pods/portforward
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - create
  - patch
# for syncer
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - delete
- apiGroups:
  - jobset.x-k8s.io
  resources:
  - jobsets
  verbs:
  - get
  - list
  - create
  - watch
  - patch
  - delete